### ISSUE TITLE
This package can't be installed on Heroku

### ISSUE THREAD

**Issue by eko24ive** [dominik791/obj-traverse#8]
**UPD: This issue was invalid at the time it was created and not relevant, please ignore**

Here is log:
```
module.js:549 
    throw err; 
    ^ 
Error: Cannot find module 'obj-traverse' 
    at Function.Module._resolveFilename (module.js:547:15) 
    at Function.Module._load (module.js:474:25) 
    at Module.require (module.js:596:17) 
    at require (internal/module.js:11:18) 
    at Object.<anonymous> (/app/index.js:10:20) 
    at Module._compile (module.js:652:30) 
    at Object.Module._extensions..js (module.js:663:10) 
    at Module.load (module.js:565:32) 
    at tryModuleLoad (module.js:505:12) 
    at Function.Module._load (module.js:497:3) 
    at Function.Module.runMain (module.js:693:10) 
    at startup (bootstrap_node.js:191:16) 
    at bootstrap_node.js:612:3 
```

Can you help me with this?

**Comment by dominik791** [comment]
Hi, double-check that the package is listed in dependencies and that you import it just like described in readme. Let me know if it helps :)

**Comment by eko24ive** [comment]
@dominik791 I'm super sorry for bothering you - it turned out that Heroku somehow treats my `package.json` in a very strange way. I had to delete it and then install each package manually. After that - I was able to deploy my app without any errors.

Sorry.

**Comment by dominik791** [comment]
no worries :)
